version: 2.1
orbs:
  pypi: pennlabs/pypi-tools@0.0.2

workflows:
  version: 2
  build-and-publish:
    jobs:
      - pypi/test:
          filters:
            tags:
              only: /.*/
      - pypi/publish:
          context: pypi-publish
          requires:
            - pypi/test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
